project_id = "wquzcrjmxgljacxaf1mj"
supabase_url = "https://wquzcrjmxgljacxaflmj.supabase.co"
supabase_key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndxdXpjcmpteGdsamFjeGFmbG1qIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDEwNjkzMTAsImV4cCI6MjA1NjY0NTMxMH0.apRO-NrIoQGUYT0c9kKW1XLl7YmDx6mMhBBvPasNHJ0"
