name: Deploy to Supabase

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Supabase CLI
        run: |
          curl -L "https://github.com/supabase/cli/releases/latest/download/supabase_linux_amd64.tar.gz" -o supabase.tar.gz
          tar -xvzf supabase.tar.gz
          chmod +x supabase
          sudo mv supabase /usr/local/bin/

      - name: Verify Supabase CLI Installation
        run: supabase --version

      - name: Authenticate with Supabase
  run: echo "${{ secrets.SUPABASE_ACCESS_TOKEN }}" | supabase login --token

      - name: Deploy Supabase Functions
        run: supabase functions deploy --project-id "${{ secrets.SUPABASE_PROJECT_ID }}"
