name: Deploy to Supabase

on:
  push:
    branches:
      - main  # Falls du eine andere Branch nutzt, ändere sie hier

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Install Supabase CLI
      run: |
        curl -L "https://github.com/supabase/cli/releases/latest/download/supabase-linux-amd64" -o supabase
        chmod +x supabase
        sudo mv supabase /usr/local/bin/
        ls -lh /usr/local/bin/supabase  # Prüfe, ob die Datei existiert (~8MB)

    - name: Prüfe Supabase Installation
      run: /usr/local/bin/supabase --version  

    - name: Authenticate with Supabase
      env:
        SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      run: echo "$SUPABASE_ACCESS_TOKEN" | /usr/local/bin/supabase login --access-token

    - name: Deploy Supabase Functions
      env:
        SUPABASE_PROJECT_ID: ${{ secrets.SUPABASE_PROJECT_ID }}
      run: /usr/local/bin/supabase functions deploy --project-id "$SUPABASE_PROJECT_ID"
