name: Deploy to Supabase

on:
  push:
    branches:
      - main  # Change this if using a different branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Supabase CLI
      run: |
        curl -fsSL https://get.supabase.com/install | sh
        echo "$HOME/.supabase/bin" >> $GITHUB_PATH  # Ensure Supabase CLI is in the path

    - name: Verify Supabase CLI Installation
      run: supabase --version  # Check if the CLI is correctly installed

    - name: Authenticate with Supabase
      run: supabase login --access-token "${{ eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndxdXpjcmpteGdsamFjeGFmbG1qIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc0MTA2OTMxMCwiZXhwIjoyMDU2NjQ1MzEwfQ.gQg8ihwtwzcZCDracSsa5f-NzBuEvqu2weRDJnMOWBA }}"

    - name: Deploy Supabase Functions
      run: supabase functions deploy --project-id "${{ wquzcrjmxgljacxaflmj }}"
