name: Deploy to Supabase 
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
    
    - name: Install Supabase CLI
      run: |
        curl -o supabase.tar.gz https://github.com/supabase/cli/releases/download/v1.164.3/supabase_1.164.3_linux_amd64.tar.gz
        tar -xzvf supabase.tar.gz
        sudo mv supabase /usr/local/bin/
        supabase --version
    
    - name: Authenticate with Supabase
      env:
        SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      run: supabase login --access-token "$SUPABASE_ACCESS_TOKEN"
    
    - name: Deploy Supabase Functions
      env:
        SUPABASE_PROJECT_ID: ${{ secrets.SUPABASE_PROJECT_ID }}
      run: supabase functions deploy --project-id "$SUPABASE_PROJECT_ID"
