name: Deploy to Supabase 

on:
  push:
    branches:
      - main  # Change this if using a different branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Supabase CLI
      run: |
        curl -fsSL https://get.supabase.com/install | sh
        export PATH="$HOME/.supabase/bin:$PATH"
        echo "$HOME/.supabase/bin" >> $GITHUB_PATH  # Ensure CLI is available globally

    - name: Verify Supabase CLI Installation
      run: |
        ls -la $HOME/.supabase/bin  # Check if Supabase CLI is installed
        which supabase  # Verify if Supabase is found in the system

    - name: Authenticate with Supabase
      env:
        SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      run: supabase login --access-token "$SUPABASE_ACCESS_TOKEN"

    - name: Deploy Supabase Functions
      env:
        SUPABASE_PROJECT_ID: ${{ secrets.SUPABASE_PROJECT_ID }}
      run: supabase functions deploy --project-id "$SUPABASE_PROJECT_ID"
