name: Deploy to Supabase 

on:
  push:
    branches:
      - main  # Change this if using a different branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Supabase CLI
      run: |
        curl -L "https://github.com/supabase/cli/releases/latest/download/supabase-linux-amd64" -o supabase
        chmod +x supabase
        sudo mv supabase /usr/local/bin/
        export PATH="/usr/local/bin:$PATH"

    - name: Verify Supabase CLI Installation
      run: supabase --version  # Check if Supabase CLI is now recognized

    - name: Authenticate with Supabase
      env:
        SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      run: supabase login --access-token "$SUPABASE_ACCESS_TOKEN"

    - name: Deploy Supabase Functions
      env:
        SUPABASE_PROJECT_ID: ${{ secrets.SUPABASE_PROJECT_ID }}
      run: supabase functions deploy --project-id "$SUPABASE_PROJECT_ID"
