name: Deploy to Supabase

on:
  push:
    branches:
      - main  # Falls du eine andere Branch nutzt, ändere sie hier

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Install Supabase CLI
  run: |
    curl -fsSL https://get.supabase.com/install | sh
    echo "$HOME/.supabase/bin" >> $GITHUB_PATH


    - name: Prüfe Supabase Installation
      run: /usr/local/bin/supabase --version  

    - name: Authenticate with Supabase
      env:
        SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      run: echo "$SUPABASE_ACCESS_TOKEN" | /usr/local/bin/supabase login --access-token

    - name: Deploy Supabase Functions
      env:
        SUPABASE_PROJECT_ID: ${{ secrets.SUPABASE_PROJECT_ID }}
      run: /usr/local/bin/supabase functions deploy --project-id "$SUPABASE_PROJECT_ID"
