name: Deploy to Supabase

on:
  push:
    branches:
      - main  # Change this if using a different branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Install Supabase CLI
      run: |
        curl -L "https://github.com/supabase/cli/releases/latest/download/supabase-linux-amd64" -o /usr/local/bin/supabase
        chmod +x /usr/local/bin/supabase
        ls -lh /usr/local/bin/supabase  # Verify file size (should be ~8MB)

    - name: Verify Supabase CLI Installation
      run: /usr/local/bin/supabase --version  # Ensure it's installed correctly

    - name: Authenticate with Supabase
      env:
        SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      run: echo "$SUPABASE_ACCESS_TOKEN" | /usr/local/bin/supabase login --access-token

    - name: Deploy Supabase Functions
      env:
        SUPABASE_PROJECT_ID: ${{ secrets.SUPABASE_PROJECT_ID }}
      run: /usr/local/bin/supabase functions deploy --project-id "$SUPABASE_PROJECT_ID"
